global:
  scrape_interval: 15s # Default is every 1 minute.
  scrape_timeout: 10s
  evaluation_interval: 15s #Check every 15 seconds for config changes
#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets: []
#      scheme: http
#      timeout: 10s
#      api_version: v1
scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['localhost:9090'] #Prometheus monitoring itself

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
#    honor_timestamps: true
